#!/bin/bash
# Wrapper script for pipeband scores
#
# It uses (standard) commandline options of lilypond
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LIB=~/projects/scoring/lib

# Change the Stylesheet variable if you want different 'settings'
# It is handy to include ./defs.ily since it defines some text variables,
# it will complain otherwise about not finding variables
#STYLESHEET=$DIR/defs.ily
STYLESHEET="$LIB/styles/pipeband.sly"

# Add lilydrum to the search path
LILYDRUM="$LIB/lilydrum/"
# Add custom bagpipe.ly to search path
BAGPIPELY="$LIB/bagpipe.ly/"

# Options by this script 
# see http://lilypond.org/doc/v2.18/Documentation/usage/command_002dline-usage#advanced-command-line-options-for-lilypond
OPTIONS="-dno-strip-output-dir -dno-point-and-click -dpaper-size=\"a4landscape\""

# Execute
lilypond -dinclude-settings=$STYLESHEET -I $LILYDRUM -I $BAGPIPELY $OPTIONS -dpreview $@
