#!/bin/bash

MKDRUMCOMMAND="./lilydrum/makedrum"
MKDRUMOPTIONS="--no-log -i ./defs/defs.ly -i ./defs/header_default.ily --drumfile ./lilydrum/lilydrum.ly --pipefile ./bagpipemusic/bagpipe_new.ly -s 18"
MUSIC_DIR="./music/"
OUT_DIR="./pdf/"
MKDRUMOPTIONS="$MKDRUMOPTIONS -d $OUT_DIR"

trap "echo Aborted!; exit;" SIGINT SIGTERM

another_dir() {
	d=$1
	for f in $d/*
	do
		if [ -d "$f" ]; then
			if [ "$f" == "template" ]; then
				continue
			fi

			another_dir $f
			continue
		fi
		if [ ! -f "$f" ]; then
			continue
		fi

		if [[ ! "$f" == *.ly ]]; then
			continue
		fi

		$MKDRUMCOMMAND $MKDRUMOPTIONS "$f"
	done;
}

if [ "$1" == "--all" ]; then
	echo "Build all"
	another_dir $MUSIC_DIR
elif [ -f "$1" ]; then
	echo "Build file"
	$MKDRUMCOMMAND $MKDRUMOPTIONS "$1"
elif [ -d "$1" ]; then
	echo "Build files in directory"
	another_dir "$1"
fi

# Fix naming
for f in $OUT_DIR/music-*
do
	mv $f ${f/music-/}
done;
